### ISSUE TITLE
音符盒的硬度

### ISSUE THREAD

**Issue by GoldenTotem** [TaoismDeepLake/noteblockne#1]
模组新添加的音符盒方块硬度为零，这导致左键音符盒时不会演奏而是摧毁。希望将新添加的音符盒与原版的音符盒匹配硬度、爆炸抗性等。
The hardness of note blocks added by the mod  is zero, which causes the note blocks to be destroyed instead of playing when left-clicking. Please match the note blocks with the vanilla note block in hardness, explosion resistance, etc.
noteblockne-1.0.0

**Comment by TaoismDeepLake** [comment]
感谢您的反馈，我会抽时间修改一下。
