### ISSUE TITLE
Sound when the note blocks are placed [音符盒放置时的声音]

### ISSUE THREAD

**Issue by GoldenTotem** [TaoismDeepLake/noteblockne#2]
The sound when the note blocks added by the mod placed or broken is like "hard block" such as stone, cobblestone. It should be the sound of "wooden block" such as planks or logs.

模组添加的音符盒被放置或破坏的声音像石头，圆石等“坚硬方块”，它应该是木板，木头等“木质方块”的声音。

**Comment by GoldenTotem** [comment]
不打算修复了？

**Comment by TaoismDeepLake** [comment]
我不是已经解决了吗，新版本都发出来了

**Comment by GoldenTotem** [comment]
> 我不是已经解决了吗，新版本都发出来了

不好意思没看见
