### ISSUE TITLE
Unnatural transitions with different types of note blocks sound [不同种类的音符盒之间的声音衔接不自然]

### ISSUE THREAD

**Issue by GoldenTotem** [TaoismDeepLake/noteblockne#3]
The note blocks will work well when there is one kind of note block, but if there are two or more kinds of note block, different kinds of note blocks will be uncoordinated and sounds strange.
当只有一种音符盒时，音符盒之间演奏得很和谐，但是有两种及以上的音符盒时，不同种的音符盒之间不协调，听起来很奇怪。

https://user-images.githubusercontent.com/70516358/122415276-5dd46780-cfba-11eb-8a51-7c57e5486b42.mp4

Just like the video, you can test it. 正如视频，你可以测试一下。

**Comment by TaoismDeepLake** [comment]
This mod us AE to edit the frequency of the audio file by 2x & 4x to fit with original file.
These note blocks should fit each other like they do in vanilla. In case they don't, there must be some unknown musical, physical or computer science theories blind to me. Until I find out why, I can not fix it.

Suggestions are welcomed from everyone.

音符盒提升音调的实现原理是使用AE把音频文件的音频抬高2倍、4倍，所以与原本的音频文件能完美地契合。
就物理学的角度，不同种的音符盒理论上也能互相契合，因为原版的就是这么契合的。如果觉得不和谐，那么很有可能是存在我不理解的乐理知识，或者计算机的仿真失真。在我搞清楚为什么之前，我无法修复这个。

也欢迎其他人贡献思路。

**Comment by TaoismDeepLake** [comment]
另外，你的视频我只能听到声音，看不到画面

**Comment by GoldenTotem** [comment]
> 另外，你的视频我只能听到声音，看不到画面

可能是github的问题，上传后没有画面，我也看不到。大致内容是：一排八个音符盒，前七个为同种的1~7（升八度）音调音符盒，第八个为高一等级音符盒的1音调。对[原，++]，[++，++++]，[--，原]都进行了一遍。

**Comment by TaoismDeepLake** [comment]
在我亲自测试的时候，前一个音符盒的最后一个音符和最后一个音符盒的第一个音符是完全一致、听不出区别的。
你确定你把音符数对了？这个非常容易数错。我没有很多的时间测试，所以我需要确保这里没有误报的bug

**Comment by TaoismDeepLake** [comment]
须知，一个音符盒是两个八度，不是一个。音符盒的默认音是中间的那个，不是最低的那个

**Comment by TaoismDeepLake** [comment]
一个音符盒放下去的时候，是最低音，可以抬高两个八度。
需要按24次，他才会成为下一个音符的第一个音。之后我再看看吧。如果单纯是因为AE处理的失真，那这个问题很难解决

**Comment by GoldenTotem** [comment]
起因是这样的，我尝试演奏一段旋律：3 5 3 2 1 6- 1 2 。除了6-，其它音调我用++音符盒低部分八度来演奏，而6-用普通音符盒的高部分八度来演奏，即所有音共同提升两个八度。开始演奏后（间隔已调整好），没有什么大问题，直到6-演奏出来时，出现了明显的不和谐，这种不和谐不像是音调的偏差，更像是音色或者延音时间的偏差。我破坏所有音符盒，6-用--音符盒的高部分八度来演奏，其它用普通音符盒的低部分八度来演奏，相当于保持原调，仍然是6-出现不和谐。再次破坏所有音符盒，用普通音符盒低部分八度演奏6-，其它用普通音符盒的高部分八度来演奏，相当于都使用普通音符盒并升调一个八度，这次没有出现不和谐。经过更多的测试，发现只要多种音符盒混用，就会在切换处不自然过渡，这种不自然不由于音调的偏差，更可能是音色或延音时间的不同。

**Comment by TaoismDeepLake** [comment]
了解了。我就说不该有音调问题。至于音色和沿音么，我研究下

**Comment by TaoismDeepLake** [comment]
我今天又戴上质量稍微好一点的耳机测试了一下，找到了一个可能导致不和谐的要素：mc在升调、降调播放声音的时候会影响播放声音的长短。播放一个音符盒的最低频有很明显的“余音绕梁”，但是调节到最高就会很短促，这是mc本身就存在的问题。
要解决这个，我想到了这么几种思路，但都不咋地：
1，写coremod修改mc底层机制——不可能。虽然这理论上可以做到，但本人从不写coremod。
2，把我的音频文件也像mc这样缩短——很愚蠢。这样会导致音调越高、音越短，高上去之后就短的没法听了。
3，彻底重新写一个音符盒，不再使用mc底层的变调机制，而是手动提供所有音频文件的25种变调——工作量太大。

事实上我也大概理解为什么mc底层播放声音的变调参数会有0.5~2的限制了，因为更夸张的变调会导致音频的持续时间更长/短，没法听。

**Comment by TaoismDeepLake** [comment]
顺便一提，我是个理科生，没有受过任何声乐训练，也不会演奏任何乐器，从未玩过红石音乐，电脑插得耳机是十块钱那种，所以……那些“不和谐”我可能根本就听不出来。像这样指出“这种不自然不由于音调的偏差，更可能是音色或延音时间的不同”对诊断问题很有帮助，在此表示感谢。

**Comment by GoldenTotem** [comment]
> 我今天又戴上质量稍微好一点的耳机测试了一下，找到了一个可能导致不和谐的要素：mc在升调、降调播放声音的时候会影响播放声音的长短。播放一个音符盒的最低频有很明显的“余音绕梁”，但是调节到最高就会很短促，这是mc本身就存在的问题。
> 要解决这个，我想到了这么几种思路，但都不咋地：
> 1，写coremod修改mc底层机制——不可能。虽然这理论上可以做到，但本人从不写coremod。
> 2，把我的音频文件也像mc这样缩短——很愚蠢。这样会导致音调越高、音越短，高上去之后就短的没法听了。
> 3，彻底重新写一个音符盒，不再使用mc底层的变调机制，而是手动提供所有音频文件的25种变调——工作量太大。
> 
> 事实上我也大概理解为什么mc底层播放声音的变调参数会有0.5~2的限制了，因为更夸张的变调会导致音频的持续时间更长/短，没法听。

升调会变短而降调会变长这个不是mc的问题，而是音乐本身的问题。像小时候在课桌边拨动钢尺发出的声音，或者拨动皮筋发出的声音，确实是长度越短，音调越高，而持续时间越短，反之亦然。在钢琴上可以印证这一点：高音比低音持续时间更短。这现象是普遍存在的，我觉得不算是一种问题。如果说是由于这个问题导致的，那么各音调之间的延音时间差距应该比较平滑，不会出现跳跃性很大的问题，这无法解释为什么使用不同种音符盒会出现较大差异，而同种音符盒之间没有明显差异的现象。所以可能不是这个原因。另外，我再次听了一遍音频，除了音色，延音之外，音量即响度也有较大差异，这有可能也是一种因素。

**Comment by GoldenTotem** [comment]
> 顺便一提，我是个理科生，没有受过任何声乐训练，也不会演奏任何乐器，从未玩过红石音乐，电脑插得耳机是十块钱那种，所以……那些“不和谐”我可能根本就听不出来。像这样指出“这种不自然不由于音调的偏差，更可能是音色或延音时间的不同”对诊断问题很有帮助，在此表示感谢。

再次回去听了一下，对于延音的问题，正常情况应该是从--的最低音到++++的最高音延音时间逐渐减小，但是根据测试结果，实际情况是--的最低音到--的最高音依次减小，切换到普通又突然增高，然后从普通的最低音到普通的最高音依次减小，后面等级的音符盒也如此。用数字来举例，正常情况应该是：100 99 98 97 96 95 ...... 6 5 4 3 2 1，一个平滑过渡的过程；而实际情况是 9 8 7 6 5 4 3 2 1  9 8 7 6 5 4 3 2 1  9 8 7 6 5 4 3 2 1 ... 。每种音符盒的延音时间不连续，出现了4个独立的过渡过程，每种音符盒独立开来，不与其它种类相衔接。而音色的问题，用一个低等级的音符盒，右击24次升调两个八度，再在旁边放置一个高一等级的音符盒。它们音调应该是相同的，实际上音调确实相同，但即使两个音符盒下面的方块相同，也像是用不同的乐器演奏一样，音色有偏差。依然是上面两个音符盒，音量也有差异。
曾经用premiere加速音频时，由于时间变短，导致频率变大，音频自然地升高音调，某些软件可能会自动地帮你调整频率至原来的音调。上述问题有可能是软件的自动修复导致的。

**Comment by TaoismDeepLake** [comment]
是这样，一个音的音高和长度是两个独立的参数。在现实世界，由于乐器物理机制的限制，不同的音，能量衰减速度不同，造成不同音高有不同音长；但是计算机模拟里可以做到独立地修改音高和音长而不改变另一者。
我这个mod在制作的时候，就是使用AE只修改音高而不修改音长。但是，mc本身调整音高却不是这样做的，他同时调整音高和音长。如果问题只有这样的话，其实还好办，我只要重新处理下，同时修改二者即可，虽然效果也会很差（高音短的要命，低音长的要命。每拉高一个八度长度缩短一半）。
至于音色、响度的问题，应该是我处理音频的时候出现了失真。音色失真没得救了。
如果你仍然想让我解决音长的问题，我下个月也许可以试试。音色的话，我基本上搞不定。响度的话……不应有区别。我自始至终没有调节过。

你可以回复我，是否希望我尝试解决音长问题。

**Comment by GoldenTotem** [comment]
> 是这样，一个音的音高和长度是两个独立的参数。在现实世界，由于乐器物理机制的限制，不同的音，能量衰减速度不同，造成不同音高有不同音长；但是计算机模拟里可以做到独立地修改音高和音长而不改变另一者。
> 我这个mod在制作的时候，就是使用AE只修改音高而不修改音长。但是，mc本身调整音高却不是这样做的，他同时调整音高和音长。如果问题只有这样的话，其实还好办，我只要重新处理下，同时修改二者即可，虽然效果也会很差（高音短的要命，低音长的要命。每拉高一个八度长度缩短一半）。
> 至于音色、响度的问题，应该是我处理音频的时候出现了失真。音色失真没得救了。
> 如果你仍然想让我解决音长的问题，我下个月也许可以试试。音色的话，我基本上搞不定。响度的话……不应有区别。我自始至终没有调节过。
> 
> 你可以回复我，是否希望我尝试解决音长问题。

如果可以的话，尝试修复一下。另外我不知道你那里是否有不自然衔接的问题，有可能你那里根本没有此问题，也可能是你没听出来。总之我想知道你自己是否有听出来不对，防止只有我这里出问题，如果可以的话，请你随便演奏点什么并录制下来，好让我核对一下是否问题一致。

**Comment by TaoismDeepLake** [comment]
等我有时间就搞搞。上周末加班了

**Comment by TaoismDeepLake** [comment]
被某些人气得健康状况开始恶化，我只处理值得的事。
Somepeople have been too annoying. I will only handle matters that matter now.

**Comment by zHElEARN** [comment]
想要提一提我的经历。

前段时间我看到了这个模组，用这个模组的音符盒制作了一首红石音乐，同样也有这个issue中的问题

我一开始以为是这个模组本身的问题，于是我提取了Minecraft原版的Harp音色然后尝试用Fabric写一个重写模组

我的步骤也是这样的：

1. 提取原版的Harp音色，原版的音调应该是F#4
2. 我使用Audition对这个音变调，升了两个八度，也就是24个半音阶（F#6）
3. 因为Minecraft的的源码中playSound有一个pitch参数是可以调整音调的，所以我只需要把F#6的音调整pitch后播放就可以了

相关代码实现如下

```java
@Override
    public ActionResult onUse(BlockState state, World world, BlockPos pos, PlayerEntity player, Hand hand, BlockHitResult hit) {
        if (!world.isClient) {
            int notePitch = state.get(NOTE);
            float pitch = (float)Math.pow(2.0D, (double)(notePitch - 12) / 12.0D);
            SoundEvent highNoteSoundEvent = Registries.SOUND_EVENT.get(new Identifier("extended-noteblock", "harp_fu6"));
            world.playSound(null, pos, highNoteSoundEvent, SoundCategory.RECORDS, 3.0F, pitch);
            state = state.cycle(NOTE);
            world.setBlockState(pos, state, 3);
        }
        return ActionResult.SUCCESS;
    }
```

那么此时原版音符盒波动24次的时候（F#5），应该要和升调音符盒中不拨动音符盒的音（F#5）一致

在测试中发现音调是一致的，但是Minecraft中playSound改变音调会把原有的音频拉长/缩短

也就是说我输入的初始音调是F#6，但是要播放F#5，通过调pitch降低了音调（F#6 -> F#5），所以导致了音频拉长

**Comment by zHElEARN** [comment]
实际上本身在Minecraft中用原版音符盒播放F#3和F#5的音频时长也不一样，修改pitch会伸缩音频

所以前文中所提到的

>1，写coremod修改mc底层机制——不可能。虽然这理论上可以做到，但本人从不写coremod。
>2，把我的音频文件也像mc这样缩短——很愚蠢。这样会导致音调越高、音越短，高上去之后就短的没法听了。
>3，彻底重新写一个音符盒，不再使用mc底层的变调机制，而是手动提供所有音频文件的25种变调——工作量太大。

第一点会影响原版的音符盒
第二点就像作者所说的那样，高音就没法听了
第三点可能是唯一可实现的方法，但是工作量非常大，还必须要提供原版音符盒的音调（因为原版音符盒有伸缩）
