### ISSUE TITLE
[1.16.5] Recipe registry done incorrectly, causing logspam anytime a recipe is unlocked.

### ISSUE THREAD

**Issue by NighthowlerStudios** [TaoismDeepLake/noteblockne#4]
this mod is causing log-spam anytime a crafting recipe is unlocked, regardless if the recipe unlocked was from your mod or not.  we believe this is because you registered the recipes incorrectly.

[18:34:51] [Server thread/INFO]: Cannot find advancement:jar
[18:34:51] [Server thread/INFO]: Cannot find advancement:sabre

**Comment by TaoismDeepLake** [comment]
Fixed.
